package com.mdjaman.lab.entity;
// Generated Nov 29, 2014 1:04:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Analyse generated by hbm2java
 */
@Entity
@Table(name="analyse"
    ,catalog="labo_db"
)
public class Analyse  implements java.io.Serializable {


     private Integer id;
     private String libelle;
     private String unite;
     private String vn;
     private Float coutHt;

    public Analyse() {
    }

    public Analyse(String libelle, String unite, String vn, Float coutHt) {
       this.libelle = libelle;
       this.unite = unite;
       this.vn = vn;
       this.coutHt = coutHt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="libelle", length=100)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="unite", length=20)
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }

    
    @Column(name="vn", length=100)
    public String getVn() {
        return this.vn;
    }
    
    public void setVn(String vn) {
        this.vn = vn;
    }

    
    @Column(name="coutHT", precision=8)
    public Float getCoutHt() {
        return this.coutHt;
    }
    
    public void setCoutHt(Float coutHt) {
        this.coutHt = coutHt;
    }




}


