package com.mdjaman.lab.entity;
// Generated Nov 29, 2014 1:04:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name="utilisateur"
    ,catalog="labo_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Utilisateur  implements java.io.Serializable {


     private Integer id;
     private Privilege privilege;
     private Utilisateur utilisateur;
     private String nom;
     private String prenom;
     private String username;
     private String email;
     private String passe;
     private String token;
     private String activcode;
     private String contact;
     private boolean actif;
     private String picture;
     private char gender;
     private Set visites = new HashSet(0);
     private Set utilisateurs = new HashSet(0);

    public Utilisateur() {
    }

	
    public Utilisateur(Privilege privilege, String nom, String prenom, String username, String email, String passe, String token, String activcode, boolean actif, char gender) {
        this.privilege = privilege;
        this.nom = nom;
        this.prenom = prenom;
        this.username = username;
        this.email = email;
        this.passe = passe;
        this.token = token;
        this.activcode = activcode;
        this.actif = actif;
        this.gender = gender;
    }
    public Utilisateur(Privilege privilege, Utilisateur utilisateur, String nom, String prenom, String username, String email, String passe, String token, String activcode, String contact, boolean actif, String picture, char gender, Set visites, Set utilisateurs) {
       this.privilege = privilege;
       this.utilisateur = utilisateur;
       this.nom = nom;
       this.prenom = prenom;
       this.username = username;
       this.email = email;
       this.passe = passe;
       this.token = token;
       this.activcode = activcode;
       this.contact = contact;
       this.actif = actif;
       this.picture = picture;
       this.gender = gender;
       this.visites = visites;
       this.utilisateurs = utilisateurs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="privilege_id", nullable=false)
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="responsable")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="nom", nullable=false, length=30)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", nullable=false, length=100)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="username", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="passe", nullable=false, length=32)
    public String getPasse() {
        return this.passe;
    }
    
    public void setPasse(String passe) {
        this.passe = passe;
    }

    
    @Column(name="token", nullable=false, length=32)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    
    @Column(name="activcode", nullable=false, length=50)
    public String getActivcode() {
        return this.activcode;
    }
    
    public void setActivcode(String activcode) {
        this.activcode = activcode;
    }

    
    @Column(name="contact", length=25)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    
    @Column(name="actif", nullable=false)
    public boolean isActif() {
        return this.actif;
    }
    
    public void setActif(boolean actif) {
        this.actif = actif;
    }

    
    @Column(name="picture", length=50)
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }

    
    @Column(name="gender", nullable=false, length=1)
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set getVisites() {
        return this.visites;
    }
    
    public void setVisites(Set visites) {
        this.visites = visites;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set utilisateurs) {
        this.utilisateurs = utilisateurs;
    }




}


